[[redirects]]
  from = "https://unlocknyc.org/*"
  to = "https://weunlock.nyc/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "/report"
  to = "/start"
  status = 301
  force = true

[[redirects]]
  from = "/record"
  to = "/start"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
   Access-Control-Allow-Origin = "*"
