[[redirects]]
  from = "/start/secure/advocate/report/*"
  force = true
  status = 200
  conditions = {Role = ["advocate"]}
  
[[redirects]]
from = "/start/secure/advocate/report/*"
to = "/start/secure/advocate/"
status = 302
force = true

[[redirects]]
  from = "https://unlocknyc.org/*"
  to = "https://weunlock.nyc/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "/report"
  to = "/start"
  status = 301
  force = true

[[redirects]]
  from = "/record"
  to = "/start"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
   Access-Control-Allow-Origin = "*"
