---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: about.md
  label: About Us
- type: directory
  path: home-slides
  label: Stories Slider
  create: all
  match: "**/*"
  exclude: home-slides.json
upload_dir: uploads
public_path: https://raw.githubusercontent.com/mab253/unlock-nyc-web/main/uploads
front_matter_path: ''
use_front_matter_path: false
file_template: 'https://raw.githubusercontent.com/mab253/unlock-nyc-web/main/uploads/:filename:'
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
